# Generated by Django 4.2.6 on 2024-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
