# Generated by Django 4.2.6 on 2023-11-07 00:31

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsInfo', '0005_day_alter_appointments_options_appointments_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(default=1, verbose_name=locations.models.Area),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('time', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'city')},
        ),
    ]
