# Generated by Django 4.2.6 on 2023-11-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_area_unique_together'),
        ('flightsInfo', '0006_package_city_alter_appointments_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.area'),
        ),
    ]
